### ISSUE TITLE
How to pass data-s parameter to solve recaptcha on google.com/sorry/index

### ISSUE THREAD

**Issue by theshahzaibc** [2captcha/2captcha-python#12]
I have read the document when we have to pass google.com search we got a value of data-s and have to pass to 2captcha. How I can pass the parameter data-s??

**Comment by 2captcha** [comment]
Just add `datas` parameter to your `solver.recaptcha` call like:

```python
try:
    result = solver.recaptcha(
        sitekey='SITEKEY',
        url='URL',
        datas='value'
        )

except Exception as e:
    sys.exit(e)
```

The API accepts both `data-s` and `datas`. That is made because in many programming languages you can't use hyphen in variable or property names. But looks like it is not documented fine enough. We'll update the docs in the nearest future.
