### ISSUE TITLE
Cloudflare Turnstile ERROR_CAPTCHA_UNSOLVABLE

### ISSUE THREAD

**Issue by bingyu50** [2captcha/2captcha-python#66]
Looks like Cloudflare Turnstile does not work now.

**Comment by RezohlazovVI** [comment]
Hi, @bingyu50! Have you been able to solve this? Was your captcha type "interactive" or "managed"? It looks like 2captcha doesn't support interactive turnstile captchas, because it works fine for managed turnstile in their API docs

**Comment by Jackson-Vieira** [comment]
Hi @RezohlazovVI,  I have same error  ERROR_CAPTCHA_UNSOLVABLEthis captcha info and the following code:

![image](https://github.com/2captcha/2captcha-python/assets/85802038/87a2ec19-dea8-482f-b9f7-a711f3c2469b)


```py
result = solver.turnstile(
    sitekey="0x4AAAAAAADnPIDROrmt1Wwj",
    url="https://cityoflapcp.ezlinksgolf.com/index.html#/search",
    data="foo",
    pagedata="cloudflare captcha",
    action="challenge",
)

print("Result: ", result)

sleep(30)

captchaId = result["captchaId"]
url = (
    f"https://2captcha.com/res.php?key={YOUR_API_KEY}&action=get&id={captchaId}&json=1"
)

response = requests.get(url)
```

can you help me?

**Comment by codingmall** [comment]
When you access a site which shows "Just a momemnt" page and says "Verify you are human by completing the action below." then when you click the checkbox it redirects to the actual site as a POST request and in the request payload it does not contain 'token' parameter at all. It sends 5 randomly named secret parameters with long encrypted values to the actual site which verifies them and allow you to move on. 

I believe this is not possible to solve using 2captcha because all 2captcha docs mentioned a single 'token' parameter everywhere. Is it right?

I have almost created a custom solution to solve those site entry captchas by the way but it is a big job and still much left do it. Can 2captcha solve it? Or should I continue with my custom solution?

**Comment by kslr** [comment]
> When you access a site which shows "Just a momemnt" page and says "Verify you are human by completing the action below." then when you click the checkbox it redirects to the actual site as a POST request and in the request payload it does not contain 'token' parameter at all. It sends 5 randomly named secret parameters with long encrypted values to the actual site which verifies them and allow you to move on.
> 
> I believe this is not possible to solve using 2captcha because all 2captcha docs mentioned a single 'token' parameter everywhere. Is it right?
> 
> I have almost created a custom solution to solve those site entry captchas by the way but it is a big job and still much left do it. Can 2captcha solve it? Or should I continue with my custom solution?

try cf_clearance in cookie

**Comment by evil1morty** [comment]
Does not work with https://ahrefs.com/backlink-checker

**Comment by codingmall** [comment]
> Does not work with https://ahrefs.com/backlink-checker

A colleague has solved it for situations like ahrefs while remain completely automatic. He will create an API now.
I have seen it working. It was amazing.

**Comment by abdul-jabbar-ms** [comment]
> Does not work with https://ahrefs.com/backlink-checker

I know somebody who has solved it for situations like you mentioned for ahrefs.
I have seen the solution working. It was amazing. Fully automatic.
